sudo: required
services:
  - docker:

before-install:
  - docker build -t shipster/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true shipster/react-test npm test

after_success:
  - docker build -t shipster/multi-client ./client
  - docker build -t shipster/multi-nginx ./nginx
  - docker build -t shipster/multi-server ./server
  - docker build -t shipster/multi-worker ./worker
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push them to dockerhub
  - docker push shipster/multi-client
  - docker push shipster/multi-nginx
  - docker push shipster/multi-server
  - docker push shipster/multi-worker

